version: '3'
services:
  rpt:
    build: .
    ports:
      - "${PORT}:8091"
    environment:
      - PORT=8091
      - TARGET_URL=${TARGET_URL}
    command: npm start
    labels:
     - "traefik.enable=true"
     - "traefik.docker.network=proxy"
     - "traefik.http.routers.${TRAEFIK_NAME}.entrypoints=websecure"
     - "traefik.http.routers.${TRAEFIK_NAME}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
     - "traefik.http.routers.${TRAEFIK_NAME}.tls.certresolver=letsencrypt"
     - "traefik.http.services.${TRAEFIK_NAME}.loadbalancer.server.port=8091"
